- a nyíl mögött legyen naracs háttér kör alakú ✅✅
- vissza nyíl ne lógjon bele a szövegbe sehol se alapértelmezetten, minden oldalt meg kell vizsgálni! ✅✅
- a footerben alulról még legyen hely. ✅✅
- név + email mező túl kicsi 50 ✅✅
FONTOS AZ Emailnál ha rányom a gombra valami betöltés kell!! ✅✅
- kapcsolat oldaln az alsó form furán müködik ✅✅
- desktop mindenki legyen ott nem kell görgethető fő oldalon az edzőknél✅✅
- weben nem kell vissza jel ✅✅
- desktop az általános szövege legyenek 24px és a title-k 32-48 ✅✅✅
-részek között padding legyen nagyobb desktop és mobile ✅✅
- footerben a logo legyen középen align-content-je. ✅✅
- hogyan dolgozunk rész desktop-n javítás 
- rólunk desktopon automatikusan menjen és majd meg lehessen állítani 
- white-t nem lehet használni. ✅✅
- desktopon-> hoverre az edzők listáját adja vissza és ha rányom akkor meg a fő részre menjen  ✅✅
-Menut még meg kell csinálni 
- helyek 

-edzés terv -> alapértelmezett ✅✅✅
-egyesületi tagság
-edzőtáborok
-egyéb